### ISSUE TITLE
UnicodeDecodeError for JSON in Solr._scrape_response

### ISSUE THREAD

**Issue by Gwildor** [django-haystack/pysolr#116]
Hello,

I'm getting UnicodeDecodeError's originating from the `_scrape_response` method of the `Solr` class. The line which causes the error can be found here: https://github.com/toastdriven/pysolr/blob/fee48b6401664c746d24f0abd9955761f5d362dd/pysolr.py#L465

My response is in JSON, and thus it can't be decoded as XML and goes into the except. It seems like this problem only occured when Sorl is returning an error. In my case, Sorl returns a 500 error, but that fact is hidden by Pysorl this way. This is the last part of my stacktrace:

```
  File "pysolr-3.1.0-py2.7.egg/pysolr.py", line 578, in search
    response = self._select(params)
  File "pysolr-3.1.0-py2.7.egg/pysolr.py", line 315, in _select
    return self._send_request('post', path, body=params_encoded, headers=headers)
  File "pysolr-3.1.0-py2.7.egg/pysolr.py", line 293, in _send_request
    error_message = self._extract_error(resp)
  File "pysolr-3.1.0-py2.7.egg/pysolr.py", line 372, in _extract_error
    reason, full_html = self._scrape_response(resp.headers, resp.content)
  File "pysolr-3.1.0-py2.7.egg/pysolr.py", line 440, in _scrape_response
    full_html = "%s" % response
```

Too be honest, I don't know why that line is even trying to transform it to a bytestring, because the response is already a bytestring as far as I can see. All I know is that it originated from 2ea84356.

**Comment by acdha** [comment]
See #123

**Comment by Gwildor** [comment]
This was not fixed in #123, because this error happens a line earlier, like @codeforkjeff explained and which can also be seen in my opening post. This issue is still present.

**Comment by acdha** [comment]
@Gwildor If you don't have time to send a patch, please add a full reproducible test case. Since this is an error-handling path reproducing it depends on your local versions and configuration.

**Comment by Gwildor** [comment]
@acdha in hindsight, I spoke too soon and you are right. I'm not sure which commit fixed this, but I can no longer reproduce this when using 3.6. I get a nice SolrError now. Guess this can finally be closed :)

**Comment by acdha** [comment]
@Gwildor thanks for the update!
