### ISSUE TITLE
I am getting a TypeError message when running "rebuild_index" with django-haystack

### ISSUE THREAD

**Issue by aaronlelevier** [django-haystack/pysolr#118]
I am getting this error:

 <pre>
File "/Users/aaron/Documents/virtualenvs/three/lib/python3.4/site-packages/pysolr.py", line 467, in _scrape_response
    full_html = full_html.replace('\n', '')
TypeError: expected bytes, bytearray or buffer compatible object
</pre>

I saw this same issue in issue #102. Has this been resolved? Or should I change some of my configuration?

I am running:
- Python 3.4.0
- Django 1.6.2
- Solr 4.8.1
- pysolr 3.2.0

Thank you,
Aaron

**Comment by cryptid11** [comment]
you have to specify the core like:

solr = pysolr.Solr('http://localhost:8080/solr/core', timeout=10)
