### ISSUE TITLE
Error in "extract" method, if spaces or special characters in the filename of the provided file object

### ISSUE THREAD

**Issue by carina21** [django-haystack/pysolr#130]
Hi all,

pysolr is a good library to communicate between python and solr server! But I found a little bug in "extract" method:
If there exists spaces or special characters in the filename of the provided file object, then occurs following error:
pysolr        ERROR   [Reason: None]
{"responseHeader":{"status":400,"QTime":1},"error":{"msg":"missing content stream","code":400}}
pysolr        ERROR   Failed to extract document metadata: [Reason: None]
{"responseHeader":{"status":400,"QTime":11},"error":{"msg":"missing content stream","code":400}}
Traceback (most recent call last):
  File "pysolr.py", line 905, in extract
    files={'file': (file_obj.name, file_obj)})
  File "/home/cw/Aptana Studio 3 Workspace/arcdoc/pysolr.py", line 321, in _send_request
    raise SolrError(error_message)
SolrError: [Reason: None]
{"responseHeader":{"status":400,"QTime":11},"error":{"msg":"missing content stream","code":400}}

To fix this bug, I added following code lines:
in line 891: filename = urllib.quote(file_obj.name)

in line 897: files={'file': (filename, file_obj)})

Here an overview of the extract method with the fixed bug:
    def extract(self, file_obj, extractOnly=True, **kwargs):
        """
        POSTs a file to the Solr ExtractingRequestHandler so rich content can
        be processed using Apache Tika. See the Solr wiki for details:

```
        http://wiki.apache.org/solr/ExtractingRequestHandler

    The ExtractingRequestHandler has a very simply model: it extracts
    contents and metadata from the uploaded file and inserts it directly
    into the index. This is rarely useful as it allows no way to store
    additional data or otherwise customize the record. Instead, by default
    we'll use the extract-only mode to extract the data without indexing it
    so the caller has the opportunity to process it as appropriate; call
    with ``extractOnly=False`` if you want to insert with no additional
    processing.

    Returns None if metadata cannot be extracted; otherwise returns a
    dictionary containing at least two keys:

        :contents:
                    Extracted full-text content, if applicable
        :metadata:
                    key:value pairs of text strings
    """
    if not hasattr(file_obj, "name"):
        raise ValueError("extract() requires file-like objects which have a defined name property")

    params = {
        "extractOnly": "true" if extractOnly else "false",
        "lowernames": "true",
        "wt": "json",
    }
    params.update(kwargs)
    filename = urllib.quote(file_obj.name)
    try:
        # We'll provide the file using its true name as Tika may use that
        # as a file type hint:
        resp = self._send_request('post', 'update/extract',
                                  body=params,
                                  files={'file': (filename, file_obj)})
    except (IOError, SolrError) as err:
        self.log.error("Failed to extract document metadata: %s", err,
                       exc_info=True)
        raise

    try:
        data = json.loads(resp)
    except ValueError as err:
        self.log.error("Failed to load JSON response: %s", err,
                       exc_info=True)
        raise

    data['contents'] = data.pop(filename, None)
    data['metadata'] = metadata = {}

    raw_metadata = data.pop("%s_metadata" % filename, None)

    if raw_metadata:
        # The raw format is somewhat annoying: it's a flat list of
        # alternating keys and value lists
        while raw_metadata:
            metadata[raw_metadata.pop()] = raw_metadata.pop()

    return data
```

Please inform me, if this bug will be fixed in the next releases!
Thanks!

**Comment by camilonova** [comment]
I hit the same bug, anything we can do about it?

**Comment by dwvisser** [comment]
+1 for me. This fixed the problem for me specifically running on Windows. I don't see the issue on Linux.

**Comment by acdha** [comment]
@dwvisser You're running the latest version of pysolr? At first glance, I would have expected `requests` to quote the payload values but if not, a pull request contributing at least a failing test would be helpful, especially if it only happens on Windows where we don't have CI coverage.

**Comment by jpatel3** [comment]
+1 Running into same.

I am running pySolr==3.6.0
The reason why it's happening is because I have special char in the filename. If I get rid of that file object, it works fine. What's the better way to handle this error?

**Comment by acdha** [comment]
@jpatel3 If you can submit a test-case which reliably fails, that'll help fix it
