### ISSUE TITLE
how to use deep paging cursorMark with pysolr ?

### ISSUE THREAD

**Issue by yspanchal** [django-haystack/pysolr#140]
results = solr.search('query', *_{'fq':'title', 'cursorMark':'_', 'sort':'id desc'})

but i cant see nextcursorMark in results. for more details using cursorMark http://heliosearch.org/solr/paging-and-deep-paging/

any solution ?

**Comment by nuarhu** [comment]
Is this pull request: https://github.com/toastdriven/pysolr/pull/142 going to be merged? I would need it, as well. The discussion seems to have diverted into a different direction.

**Comment by swistakm** [comment]
+1

**Comment by swayson** [comment]
+1

**Comment by bendemott** [comment]
+1

**Comment by acdha** [comment]
Support was merged in #142.
