### ISSUE TITLE
Issue when converting a multi-valued Solr field to native python type

### ISSUE THREAD

**Issue by vmendiratta** [django-haystack/pysolr#144]
I'm on Solr 4.2 and I'm observing a strange behavior when converting a multi-valued Solr field to native python type.
The issue seems to originate in the method _to_python (of the python class Solr), specifically line number 525-526:

if isinstance(value, (list, tuple)):
    value = value[0]

Not sure why we just pick & return the first value from the list. In previous pysolr versions, this was working fine when we picked and returned the entire "value".

Had this been an issue, I don't think it would have remained undetected for this long. So, this makes me question what I'm doing wrong. Filing this issue in the off-chance there are others who are also experiencing this.

**Comment by vmendiratta** [comment]
So, after a few weeks of extensive testing and running live in production, we haven't seen any adverse effect of returning the entire list (instead of just the first element).
I'm not sure how could I be the only one complaning. Please feel free to reject the issue until someone else also complains.

**Comment by acdha** [comment]
I'm inclined to roll this into the next major release. I wonder whether it'd make sense to add a DeprecationWarning first to increase the odds of anyone noticing first.

**Comment by saily** [comment]
@vmendiratta @acdha any news on this? just ran into same issue. what's missing here? because fix seems pretty easy.

**Comment by vvolkman** [comment]
+1 to fix
