### ISSUE TITLE
Add support for replication API

### ISSUE THREAD

**Issue by nofeet** [django-haystack/pysolr#156]
I would find it useful if pysolr could trigger replication commands, like enable/disable replication and create a backup. [Here is the API documentation.](https://wiki.apache.org/solr/SolrReplication#HTTP_API)

I've written some basic code to do this. I can complete it, add tests, and submit it as a pull request if this you think this should be part of pysolr. What do you think?

**Comment by vvolkman** [comment]
+1

**Comment by acdha** [comment]
A pull request, particularly with tests, would be most welcome

**Comment by nofeet** [comment]
Since there are 11 methods in the replication API and their behavior and set-up are a little different than what's already been done in pysolr, I pushed code and tests for just 3 of them so far to make sure I'm on the right track: https://github.com/nofeet/pysolr/commit/0593eb8

What do you think?
