### ISSUE TITLE
Assumptions fail and leaky abstractions

### ISSUE THREAD

**Issue by swistakm** [django-haystack/pysolr#166]
I use pysolr because there is nothing better yet. Sadly every time I need to do something unusual I'm stuck because pysolr makes some painful assumptions about what I wan't to do. Most of all it makes assumptions about what parts of response I'm interested in and does not give me anything more.

Currently we can access only those fields that:
1. are accessed as attributes of `Results()` class
2. `Solr()` class API methods kindly pass to `Results()` class as instance args/kwargs

This approach has following problems:
1. This isn't future-proof. Whenever something new is added to Solr, pysolr users can't access it because assumption was made ("you ain't gonna need that") and can't do nothing about that. Only solution is to add a new "feature" as a PR that lands in limbo (#140, #141, #148, #142, #55; note that some of them are years old!).
2. There is no separation of concerns. `Results()` do nothing more than storing fields. It really could be a dict. There is almost no benefit in using object here. And most of the code in methods like `search()` is creating a result field by field:
   
   ```
   if result.get('stats'):
       result_kwargs['stats'] = result['stats']
   ```
   
   This IMHO should be a responsibility of `Results()` class - take a raw response an make it something more python-like. As a side note i feel that the need for altering this response is doubtful.
3. Cognitive burden - result attributes are different from those used in Solr (like: `qtime` vs. `QTime`). So if you are well familiar with Solr you need to remember two sets of results fields. Also if someone wants to switch to `pysolr` due to other features then migration of existing code can be tedious because of that. 
4. Introducing new solr features requires new tests while it actually should not. Since Solr is quite mature project there is no need to tests things that are documented and outside of the lib scope. But since every not covered response field becomes actual `Results()` class and `Solr()` class code it becomes pysolr's feature and thus needs testing. Take for example the `cursorMark` proposed by #140 & #141.
5. Too much maintenance. Every new field needs new code. Trivial or not this creates need for PRs, reviews, merging, releases. No one likes doing that for trivial code so this is the reason of so long PR backlog piling up on GitHub.

But hey! pysolr is generally good but not "future proof" and thus needs constant care from maintainers. So much that they lost the steam and this is the reason than mentioned PR-limbo exists. This isn't a vicious rant. I have suggestion how to fix this situation in a few steps:
1. quick hotfix so impatient devs (like me) can still can use pysolr despite the fact it does not assumed there are features they would like to use. Solution is simple: make `Results()` object contain also a raw solr response dictionary. Like:
   
   ``` !python
   def search(self, q, **kwargs):
      params = {'q': q}
      params.update(kwargs)
      response = self._select(params)
   
      result = self.decoder.decode(response)
      result_kwargs = {}
      # nasty "dicting" here
      # ...
      response = result.get('response') or {}
      numFound = response.get('numFound', 0)
      # `raw_result=result` for those that we forget about
      return Results(response.get('docs', ()), numFound, raw_result=result, **result_kwargs)
   ```
2. code refactoring to improve separation of concerns between Client and Results class. Let client api methods like `Solr.search()` pass whole response json to `Results()` class instead of creating intermediary dict and then unpacking it into Results args and/or kwargs like:
   
   ```
   def search(self, q, **kwargs):
      params = {'q': q}
      params.update(kwargs)
      response = self._select(params)
   
      return Results(self.decoder.decode(response))
   ```
3. pluggable results classes so you could extend existing `Results()` class if something is missing via subclassing without the need for fixing whole pysolr package. Or even replacing whole stuff with something different. Like:
   
   ``` !python
   class Solr(object):
   
      def __init__(self, url, decoder=None, timeout=60, results_cls=Results):
          self.decoder = decoder or json.JSONDecoder()
          self.url = url
          self.timeout = timeout
          self.log = self._get_log()
          self.session = requests.Session()
          self.session.stream = False
          self.results_cls = results_cls
   
      # ...
   
      def search(self, q, **kwargs):
          params = {'q': q}
          params.update(kwargs)
          response = self._select(params)
   
          return self.results_cls(self.decoder.decode(response))
   ```
   
   With that you can even do `solr = pysolr.Solr(url, response_cls=dict)` and have exactly the same thing you would get using something like only `requests` but still benefitting from anything else `Solr` class provides you.
4. Future improvements in existing `Results` class. I'm sure there is a mass of people appreciating fact that you can access response fields via attributes instead of just keys (sadly, I'm not one of them) but maybe there is a way to make it more generic and future proof so there is no need to iterate over every Solr response field. Im sure there is a way to make it more auto-magical and still ensure backwards compatibility.

All those steps ensure backwards compatibility (except 4. that is like optional) while making `pysolr` compatible with a load of existing Solr's features like cursors, maxScore etc and more that even does not exist yet. This will in fact reduce overall amount of code and make pysolr more maintainable (lot of existing PRs could be closed).

I can handle code changes and prepare PRs for every step described here (or just jump to 3.) but I would like to be sure that someone agrees with me and wants at least to review proposed changes.

**Comment by swistakm** [comment]
Hah, found [this line](https://github.com/toastdriven/pysolr/blame/master/pysolr.py#L636) that is here from the [very beginning of pysolr](https://github.com/toastdriven/pysolr/commit/8e4c671829c066531ec30aea3e134bb6070aeb64):

    # TODO: make result retrieval lazy and allow custom result objects

So I did not wait and just did it (#167)

**Comment by acdha** [comment]
I owe you a longer response but I'm :+1: on doing this. pysolr is a fairly old project and long-overdue for some refactoring.
