### ISSUE TITLE
Solr.add supports commitWithin but not overwrite

### ISSUE THREAD

**Issue by robinsonkwame** [django-haystack/pysolr#181]
I have a use case for setting the overwrite attribute of the add tag to False.

Currently only the commitWithin attribute is supported. This could be done very simply by including overwrite as a Solr.add parameter and setting the message with its value if defined.

**Comment by acdha** [comment]
If you want to send a pull request, I can review it.

**Comment by robinsonkwame** [comment]
Thanks. See: https://github.com/toastdriven/pysolr/pull/182
