### ISSUE TITLE
Pass through HTTP error codes

### ISSUE THREAD

**Issue by haveaguess** [django-haystack/pysolr#183]
Currently when executing huge queries, when the Solr server times out PySolr generates a generic error, and doesn't give us access to the low-level HTTP code or message of the failure

It makes sense to let the user get access to the low level failure 

Our user story is we want to tell the user that they are running a large query that has timed out, and that they might want to consider reducing the size of their query

**Comment by acdha** [comment]
Here's where SolrError is raised. It sounds like you might have two problems – one being that the extracted error message isn't helpful and the other being that we should just put the status on the `SolrError` before raising it:

https://github.com/toastdriven/pysolr/blob/master/pysolr.py#L390-L396

Thinking about this, maybe we should make a `SolrHTTPError` subclass of SolrError (and mixin `HTTPException` so generic exception handlers will do the right thing) which always has a `request` property for the original request and will have a `response` property anywhere that's possible (i.e. everything higher-level than low-level network errors). That'd allow you to check status codes, view a redirect chain or authentication credentials, etc.
