### ISSUE TITLE
Optimize should support 'commit' flag as well

### ISSUE THREAD

**Issue by dhruvpathak** [django-haystack/pysolr#191]
The optimize() operation should also allow commit=true/false flag being sent to update().
Currently it only supports waitSearcher, waitFlush, and maxSegments.

`def optimize(self, waitFlush=None, waitSearcher=None, maxSegments=None):`

can be :

`def optimize(self, waitFlush=None, waitSearcher=None, maxSegments=None, commit=True):`

**Comment by acdha** [comment]
@dhruvpathak sounds good - can you send a pull request?

**Comment by dhruvpathak** [comment]
The change is now merged. Is it now available in the pypi package as well ? 
https://pypi.python.org/pypi/pysolr/

**Comment by acdha** [comment]
@dhruvpathak There will be a release soon but there's a good bit of testing still required – see https://github.com/django-haystack/pysolr/compare/v3.4.0...master for everything which has changed. If you have spare time to help with review and testing, that would be appreciated.
