### ISSUE TITLE
unicode problem

### ISSUE THREAD

**Issue by joln** [django-haystack/pysolr#194]
results.docs

response like this

[{u'text': [u'\u65b0\u6d6a\u5a31\u4e50\u8baf n']

I don't want to show html like this

**Comment by acdha** [comment]
It's not clear what's wrong with your application but without a reproducible test case, there's not much to go on here. Solr and pysolr all handle Unicode correctly and this combination is heavily used in general.

Feel free to reopen this issue with the full step-by-step instructions for reproducing the problem.
