### ISSUE TITLE
Issue with date

### ISSUE THREAD

**Issue by savalou** [django-haystack/pysolr#197]
# I have
* [x] Tested with the latest release
* [ ] Tested with the current master branch
* [ ] Searched for similar existing issues

## Actual behavior
 Trying to index some data in django, when I run ./manage.py build_index, I get the following:
```
File "/home/vagrant/django/local/lib/python2.7/site-packages/pysolr.py", line 386, in _send_request
    raise SolrError(error_message % (resp.status_code, solr_message))
SolrError: Solr responded with an error (HTTP 400): [Reason: Invalid Date in Date Math String:'2016-05-26T16:43:04.644145+00:00Z']
```

## Steps to reproduce the behaviour

1.

## Configuration

* Search engine version: Solr 6.0.0
* Python version:Python 2.7.6
* pysolr version: pysolr-3.5.0

**Comment by pembo13** [comment]
Running into the very same issue.

The problem is a naive datetime yields a different format than a timezone aware version:

```python
import pytz
from datetime import datetime
datetime.utcnow().isoformat()
datetime.utcnow().replace(tzinfo = pytz.utc).isoformat()
```
yields

```
'2016-06-16T18:44:24.746108'
'2016-06-16T18:44:26.169965+00:00'
```

The problem seems to be in `pysolr`, in it's `_from_python` method.

Changing

```python
value = "%sZ" % value.isoformat()
```
to
```python
value = "%sZ" % ( value.strftime('%Y-%m-%dT%H:%M:%S.%f') if value.tzinfo else value.isoformat() )
```
fixes the problem, but I'm not sure that that's the best way to do it.

**Comment by pembo13** [comment]
Can someone take a look at Pull #198
