### ISSUE TITLE
Delete specific fields from a document

### ISSUE THREAD

**Issue by anavaleije** [django-haystack/pysolr#199]
# I have
- [X] Tested with the latest release
- [X] Tested with the current master branch
- [X] Searched for similar existing issues
## Expected behaviour

Solr allows deleting a field by providing the null attribute to an add operation. In the [example](https://wiki.apache.org/solr/UpdateXmlMessages#Optional_attributes_for_.22add.22) below, the field skills should be deleted from the document with "employeeId" 05991:

``` xml
<add>
    <doc>
        <field name="employeeId">05991</field>
        <field name="skills" update="set" null="true" />
    </doc>
</add>
```

I would expect that the following call would be equivalent to the xml above:

``` python
docs = [{'empolyeeId':05991, 'skills':None}]
solr.add(docs, fieldUpdates={'skills':'set'})
```
## Actual behaviour

As far as I understand, this operation is not yet supported in pysolr. I could not find a way to input the null attribute to the add method of Solr class.
## Configuration
- Operating system version: Ubuntu 14.04, kernel 3.16.0-77-generic
- Search engine version: 4.7
- Python version: 2.7.6
- pysolr version: 3.5.0

**Comment by jogilder** [comment]
hi, I am having the same problem. I would like to be able to delete a specific field using the set and null options. I can get this to work by passing in a new dictionary fieldNull=None to add and treating it in the same way as fieldUpdates, creating an attribute null and setting the values to true. To make it work at all I need to take out if self._is_null_value(bit): and it doesn't work for multivalued fields because of the for bit in values loop.
 #150  - is this still necessary? 
Maybe set needs to have it's own method to allow for the empty list and setting of null for single value fields.

**Comment by dustyny** [comment]
@jogilder can you please post code for your work around. I'm trying to figure out how to do the same but I'm not having any luck.

**Comment by jogilder** [comment]
Hi, I updated the _build_doc method. At the moment it doesn't do anything if there is a 'null value' passed. I have added in an extra check if the user passes in an empty string or list and they are doing a 'set' fieldUpdate then it will add in the document but will also add an extra attribute null=true. This works for me as I am passing in empty lists, it wouldn't work if someone passed in field=None.
`

    def _build_field(self, value, key, _atomic_update_set, boost=None, fieldUpdates=None):
        attrs = {'name': key}
        if fieldUpdates and key in fieldUpdates:
            attrs['update'] = fieldUpdates[key]
            if self._is_null_value(value) and _atomic_update_set:
                attrs['null'] = u'true'
        if boost and key in boost:
            attrs['boost'] = force_unicode(boost[key])
        field = ElementTree.Element('field', **attrs)
        field.text = self._from_python(value)
        return field

    def _is_atomic_update_set(self,field_update_text):
        _atomic_update_set = False
        if field_update_text.lower() == "set":
            _atomic_update_set = True
        return _atomic_update_set

    def _build_doc(self, doc, boost=None, fieldUpdates=None):
        doc_elem = ElementTree.Element('doc')
        for key, value in doc.items():
            if key == NESTED_DOC_KEY:
                for child in value:
                    doc_elem.append(self._build_doc(child, boost, fieldUpdates))
                continue

            if key == 'boost':
                doc_elem.set('boost', force_unicode(value))
                continue

            _atomic_update_set = self._is_atomic_update_set(fieldUpdates.get(key, u''))
            # To avoid multiple code-paths we'd like to treat all of our values as iterables:
            if isinstance(value, (list, tuple)):
                values = value
                #we want to be able to do the for loop if we have an empty list
                if _atomic_update_set and not values:
                    values = (u'',)
            else:
                values = (value, )
            #if this is a list then we go through the list or tuple - doesn't work for an empty list
            for bit in values:
                #allow empty strings if this is a set update but create null attribute
                if self._is_null_value(bit) and not _atomic_update_set:
                    continue
                field = self._build_field(bit, key, _atomic_update_set, boost, fieldUpdates)
                doc_elem.append(field)
        return doc_elem
`

**Comment by dustyny** [comment]
@jogilder thank you, I really appreciate it. I've been spending a lot of time trying to figure out how to handle atomic updates. I'd like to test this today. Could you give me an example of how I would call this?

**Comment by jogilder** [comment]
dict_for_doc = {'UUID': obj_source_id,  'book_book_ref_ids':[]}
    docs.append(dict_for_doc)
    field_updates = {'book_book_ref_ids':'set'}
    pysolr.Solr.add(docs,fieldUpdates=fieldUpdates)

This is pseudo code as my call gets very complicated. Basically create the document you want to add to solr with the empty fields, add in the set fieldUpdates and it should work...

**Comment by dustyny** [comment]
@jogilder I'll give it a try. thanks for the quick reply.

**Comment by jogilder** [comment]
so is this fixed then?
