### ISSUE TITLE
Documentation is...lacking.

### ISSUE THREAD

**Issue by mlissner** [django-haystack/pysolr#202]
I'm curious if there is an appetite for better documentation. I'm just trying out PySolr, and I can't find anything beyond the readme. 

I have:
- [x] Googled
- [x] Looked in the code
- [x] Read the readme
- [x] Looked at the Wiki
- [x] Searched in the issues

As a first pass, it seems worthwhile to simply expand the readme so that it has more details. Long term, I guess we'll want something more official, like a page on readthedocs or something, but there's value in keeping the infrastructure simple, at least at first.

A few things I've already run into just in my own exploration:
- What does results.docs.count() do? How do I call it? 
- How can I do pagination of results? Will it just work with Django? 
- How does r.grouped work? 
- How does r.highlighting work? 

These are things I'll be figuring out, but I'd love if there was more detailed documentation of all this, as well as a process for updating the documentation if a PR adds a new feature. 

Any appetite? If so, any way to ping the group and seek input as to what else should go into this kind of a guide? I can probably send a PR to the readme with a number of these things if this is something we're interested in.

**Comment by acdha** [comment]
We definitely could use some documentation improvements. It's probably time to reconsider migrating everything to Sphinx so we could have pysolr.readthedocs.org work as it does for Haystack, especially since some of the newer work on e.g. SolrCloud / ZooKeeper opens up a considerable amount of complexity.

**Comment by XciA** [comment]
At least a few examples could have helped.Why there is no documentation?

**Comment by acdha** [comment]
@XciA There is documentation: https://github.com/django-haystack/pysolr#usage

Is it complete? Of course not, but everyone knows that — it's always been a question of people having time to improve things. If you have specific improvements in mind, please open a pull request with your proposed changes.
