### ISSUE TITLE
type error while inserting a document into solr

### ISSUE THREAD

**Issue by kayvan90** [django-haystack/pysolr#215]
# I have
*  Tested with the latest release
*  Tested with the current master branch
*  Searched for similar existing issues

## Unusual behavior
pysolr turns some of my integer ids of documents into string and send it to my database, therefore I get value error from the solr database!
I have tracked the pysolr and somewhere in the middle of the code this happens! could someone please let me know why this happens and how can I fix it?

### this is an error I face:
Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=B*****WD-7e] Error adding field 'owner_id'='2212682169' msg=For input string: "2212682169"]
while I send integer to pysolr

## Configuration

* Operating system version: centos 7
* Python version: 2.7
* pysolr version: latest from the github

**Comment by swistakm** [comment]
I think than no one will be able to help without:
* excerpt from Solr schema xml file,
* excerpt from your code that uses pysolr

**Comment by kayvan90** [comment]
> swistakm:
> I think than no one will be able to help without:
>     excerpt from Solr schema xml file,
>     excerpt from your code that uses pysolr

dear @swistakm here is some excerpt from Solr xml and my code:

this is how the field is defined in solr xml:
`  <field name="owner_id" type="int" indexed="true" stored="true" omitNorms="true"/>
`
here is a sample doc to be add to my database:
`new_doc = {
...
owner_id:2212683215
...
}`

and I simply use the below code to insert the newly created doc to my database:
`solr.add(new_doc)`

but unfortunately some of the times(not all the time) I'll face this error:
`Solr responded with an error (HTTP 400): [Reason: ERROR: [doc=B*****WD-7e] Error adding field 'owner_id'='2212682169' msg=For input string: "2212683215"]`

**Comment by swistakm** [comment]
I have some idea, but to be completely sure I would have to see the `schema.xml` part where your field types are defined.

You said that some of the times it works as expected. Note that your example value is `2212682169` and this is bigger than `2147483647` (largest value for signed 32 bit int). I suppose that `type="int"` is defined as default `TrieIntField`:

```xml
<fieldType name="int" class="solr.TrieIntField" precisionStep="0" positionIncrementGap="0"/>
```

If you have such big values then in my opinion the solution would be to change the field type to 64 bit value i.e. `TrieLongField`:

```xml
<fieldType name="long" class="solr.TrieLongField" precisionStep="0" positionIncrementGap="0"/>
```

Still it may not be a best fix. I can give better suggestions without know anything more about your data and how do you want to access it. For instance, if your `owner_id` is not real integer value but any arbitrarily long sequence of digits it is possible that 64bit long value is not enough (largest value is 9223372036854775807 and it is only. In such situation it would be better to have it indexed as simple string value.

Additional thisng to consider when designing your Solr schema:
* does the `owner_id` needs to be retrieved or it is only used in exact match queries. If not then using string type with  `stored="false"` should be relatively lightweight and would also save you from errors like the one described here.
* note that `TrieIntField` and `TrieLongField` are designed to support range queries and efficient sorting and this can be tuned with `precisionStep` parameter (0 for sorting, 8 for range queries). I guess `owner_id` is identifier and you don't want to sort and use range on that field.
* It is interesting that older Solr versions (pre 5.0) had also `IntField` and `FloatFields` available that stored integers as simple strings. They are deprecated and if you really want to store your identifiers as integers use their `Trie*` versions. Anyway, it means that there are some situations where it may make sense to treat something as a string even if it looks like ordinary number.

Sidenote: Note that pysolr will send your document as XML and there is no place where it could mispresent numbers as strings (this could be possible for JSON). This is is one of the reasons why you need to define data types in Solr schema.
