### ISSUE TITLE
Question about coroutines and asyncio

### ISSUE THREAD

**Issue by danizen** [django-haystack/pysolr#219]
This is not a bug but a question.   Does pysolr work well with python asyncio, eventlet, and/or other co-routines?   I understand that the urllib and requests libraries may work, but I wonder whether more is needed at the software library level.

**Comment by vvolkman** [comment]
We use pysolr with the multithreading library on Python 3.  We often have as many as eight threads doing different  queries at any one time.

**Comment by acdha** [comment]
It's not designed to be async itself but there shouldn't be any shared state on the `Pysolr` objects preventing you from using them in a concurrent app. I use them in threaded contexts w/o issue normally and the underlying `requests` module is, of course, fine.

**Comment by danizen** [comment]
Thanks - I'm going with Java for this application, but it is good to know...
