### ISSUE TITLE
Test suite should run for multiple solr versions

### ISSUE THREAD

**Issue by efagerberg** [django-haystack/pysolr#223]
Currently pysolr's test suite only runs on Solr 4.10.4

According to http://django-haystack.readthedocs.io/en/master/backend_support.html pysolr supports 3.5+ but the test suite does not reflect that initiative.

The tests should be able to run against many versions of Solr in order to assert that pysolr works with those versions.

**Comment by acdha** [comment]
Yes — do you have time to contribute a pull request? These days it should be easier to do since the Solr project now publishes Docker images: https://hub.docker.com/r/library/solr/tags/

**Comment by efagerberg** [comment]
Yeah I will have a good think on how we can do this easily with travis and docker solr.

**Comment by acdha** [comment]
Much appreciated — I've been meaning to look into that since Travis announced Docker support but work & personal life have interfered.

**Comment by efagerberg** [comment]
Hello wanted to update this issue. @jnovinger has been working on this in his branch https://github.com/jnovinger/pysolr/tree/test/multiple-solr-versions

@acdha  Expect the PR from him for this sometime soon

**Comment by acdha** [comment]
Excellent, thanks!
