### ISSUE TITLE
search query escape function

### ISSUE THREAD

**Issue by ergo** [django-haystack/pysolr#23]
would it make sense to make an escape function for raw data used in searches and include it within lib itself?

something like this

``` python

def solr_escape(input):
    special_chars = ["\\", '+', '-', '&&', '||', '!', '(', ')', '{', '}', '[', ']',
                  '^', '"', '~', '*', '?', ':']
    for char in special_chars:
        if char in input:
            input = input.replace(char, '\\' + char)
    return input

```

**Comment by thomasbilk** [comment]
So.

**Comment by swistakm** [comment]
@thomasbilk, @ergo: take a look at [solrq](https://github.com/swistakm/solrq). It escapes queries for you and also adds some more nice features. It can be used with pysolr or any other python solr client.

**Comment by torfsen** [comment]
Please note that `/` is also a reserved character [since Lucene 4](http://lucene.472066.n3.nabble.com/Solr-4-upgrade-guide-tp4001779.html).

**Comment by torfsen** [comment]
Please note that `/` is also a reserved character [since Lucene 4](http://lucene.472066.n3.nabble.com/Solr-4-upgrade-guide-tp4001779.html).
