### ISSUE TITLE
pysolr.extract() fails if spaces or special characters in filename

### ISSUE THREAD

**Issue by dwvisser** [django-haystack/pysolr#237]
I'm basically re-opening #130 here. See the issue description there, as well as my pull request which fixes this: #234

**Comment by acdha** [comment]
This was merged on July 9th

**Comment by dwvisser** [comment]
Cool. Any thoughts on doing, say, a 3.7.1 release?

Sent from my 📱
________________________________

**Comment by acdha** [comment]
I haven't really had time to test it much but v3.8.0 is now out

**Comment by acdha** [comment]
Errr, make that v3.8.1 due to different repo config on this machine

**Comment by dwvisser** [comment]
👍

Sent from my 📱
________________________________
