### ISSUE TITLE
Query security

### ISSUE THREAD

**Issue by GrazingScientist** [django-haystack/pysolr#239]
## Configuration

* Operating system version: Suse Linux
* Search engine version: Solr 7.2
* Python version: 3.4
* pysolr version: 3.7.0

Dear all,

since I realized that pysolr simply parses the user string to Solr, I wanted to ask if there are any security measures that I did not see? 

Since I read [here](https://github.com/dergachev/solr-security-proxy) that simpy adding the user query can be a very BAD thing, I am slightly afraid.

If there is no security check in pysolr, do you have any recommondations for packages that do this?

Thanks for any response!

**Comment by acdha** [comment]
That document is talking about something else: exposing the Solr REST endpoints directly. If you have a normal app using pysolr you are only using user input for the actual query text rather than all of its parameters and don't give the client the option of selecting things like the update handler.

**Comment by GrazingScientist** [comment]
Okay! Thanks for the repsonse! I am feeling better now!
