### ISSUE TITLE
Close Zookeeper Sessions

### ISSUE THREAD

**Issue by nehmetohme** [django-haystack/pysolr#242]
Zookeeper session needs to be closed in the Zookeepr class.

    def closeZKSession(self):
        self.zk.stop()

**Comment by nehmetohme** [comment]
I am calling it from a pyspark. ZK is reaching the session limit and in turn, blocks new connections. By adding a close I was able to solve the issue. Also the proper implementation is to use a client-id in kazoo and reuse it. 

    df = spark.sql("select product_name from avro")
    df = df.filter("product_name like 'xyz%'")
    def solrCall(query):
        try:
            zookeeper = pysolr.ZooKeeper("server.fqdn:2181/solr")
            solr = pysolr.SolrCloud(zookeeper, "product")
            print solr
            result = solr.search( query, rows=1)
        except:
            return "Error"

    solrCall = udf(solrCall, StringType())
    df = df.withColumn('responseCode', lit(solrCall(df.product_name)))

**Comment by acdha** [comment]
For performance, wouldn't you want to create your solr & zookeeper objects once rather than accumulating large numbers of them anyway?

You should be able to make it work simply by doing `del zookeeper, solr` when you're done with them but it'll certainly be churning a lot of initialization overhead.

**Comment by nehmetohme** [comment]
I agree it is somewhat chatty but my issue is that I am not able to serialize the solr object across the executors. It would be ideal if I can establish those sessions once initially and then reuse them within the spark executors.

**Comment by nehmetohme** [comment]
I tried also to open the sessions at the partition level and not the element level and something bizarre is happening. I am getting back only a fraction. Could that be because we are not using the session ID in kazoo?

Zookeeper Log
2018-09-12 07:58:25,133 WARN org.apache.zookeeper.server.NIOServerCnxn: caught end of stream exception
EndOfStreamException: Unable to read additional data from client sessionid 0x16xxxxa43970616, likely client has closed socket
	at org.apache.zookeeper.server.NIOServerCnxn.doIO(NIOServerCnxn.java:231)
	at org.apache.zookeeper.server.NIOServerCnxnFactory.run(NIOServerCnxnFactory.java:208)
	at java.lang.Thread.run(Thread.java:745)
2018-09-12 07:58:25,134 INFO org.apache.zookeeper.server.NIOServerCnxn: Closed socket connection for client /x.x.x.x:53976 which had sessionid 0x165cc3a43970616

    
def f(iterator):
         zookeeper = pysolr.ZooKeeper("server.fqdn:2181/solr")
         solr = pysolr.SolrCloud(zookeeper, "product",  timeout=10)
         for x in iterator:
             print("iterator")
             try:
                 solr.search(x, rows=1)
                 print(x)
             except:
                 print "Error"
                 return "Error"
         print("====")

    data = df.rdd
    data.foreachPartition(t)
    data.foreachPartition(f)

**Comment by acdha** [comment]
Does manually deleting the objects as above solve the problem?
