### ISSUE TITLE
Atomic/Partial updates by using pysolr

### ISSUE THREAD

**Issue by gokul180288** [django-haystack/pysolr#248]
# I have
* [x] Tested with the latest release
* [ ] Tested with the current master branch
* [ ] Searched for similar existing issues

## Steps to reproduce the behaviour

Unable to do Atomic/Partial updates by using pysolr:
Here is the code,
solr = pysolr.Solr('http://xxx.xxx.xx.xx/solr/data-core/')
df = data.to_json(orient='records')
solr.add(json.loads(df))

The problem is that my document gets always overwritten completely and I lose the previous fields.
## Configuration

* Operating system version:
* Search engine version:
* Python version: 3.7
* pysolr version:

**Comment by gokul180288** [comment]
Unable to do Atomic/Partial updates by using pysolr:
Here is the code,
solr = pysolr.Solr('http://xxx.xxx.xx.xx/solr/data-core/')
df = data.to_json(orient='records')
solr.add(json.loads(df))

The problem is that my document gets always overwritten completely and I lose the previous fields.

**Comment by acdha** [comment]
That's because you've asked pysolr to do a full update. If you want to update specific fields, provide that list: https://github.com/django-haystack/pysolr/blob/7852f379b42075bf0088ebedaa77ff6c475f6ccc/CHANGELOG.rst#v330-2015-02-03
