### ISSUE TITLE
Iterate through a cursor

### ISSUE THREAD

**Issue by ke4roh** [django-haystack/pysolr#251]
# I have
* [X] Tested with the latest release
* [X] Tested with the current master branch
* [X] Searched for similar existing issues

## Expected behaviour
The Results object offers an iterator over a cursor of results.

## Actual behaviour
I have to write/run something like this code every time I want to iterate through a cursor:

```
def iter_records(solr, **qparams):
    result = solr.search(**qparams)

    while True:
        for doc in result.docs:
            yield doc
        if result.raw_response['responseHeader']['params'].get('cursorMark',None) == result.raw_response.get("nextCursorMark",None):
            break
        qparams['cursorMark']=result.raw_response["nextCursorMark"]
        result = solr.search(**qparams)
```
## Steps to reproduce the behaviour

```
solr = Solr(...)
result = solr.query(q="*:*",cursorMark="*",sort="id asc")
for doc in result:
    print(str(doc))
```
(This implies one particular implementation, which may not be the best, but it's a start.)

## Configuration

* Operating system version: any
* Search engine version: any
* Python version: 3.6
* pysolr version: 3.7.0

**Comment by ke4roh** [comment]
I have a patch for this which passes a lambda function to the Results object to keep track of how to search (parameters and which Solr instance).

Regarding the iterator implementation, we don't want to break the existing behavior - iterating through results.docs should return the docs retrieved, and so forth.  A separate iterator is in order.  A list (or tuple) is not appropriate because we have no guarantee that the entire result set might fit in memory.  The __iter__() function seems to me like a reasonable enough place to put the feature.  (Will people find it?)

**Comment by ke4roh** [comment]
Another thought I had about implementation is that we *could* mimic the behavior of an array for those who want it, with the primary use case being the iterator.  The drawback would be that it would take O(N) time to get to any element in the array, unless it happened to be in the current Result.  Caching could expedite many cases (caching neighboring results and tracking incices for a finite number of cursorMarks), but that seems like a lot of work for something that is fundamentally an iterator.

**Comment by acdha** [comment]
Yeah, I'm generally in favor of not adding caching without some sort of clear user-visible indication that potentially non-trivial amounts of memory will be used. I think an iterator is a good fit for this as long as it has a reasonable chunk size so we don't hide a huge number of requests.

**Comment by ke4roh** [comment]
The chunk size is up to the user - they're going to ask solr to give so many rows (or default to 10), and they have some notion of how many rows there are (or they should check before iterating a long time), so should expect the number of calls to be ceil(numFound/rows).  The iterator approach offers more granularity on that front than most database drivers expose, so I think it's solid.

**Comment by ke4roh** [comment]
Pull request #252 is an implementation.  It passes tests.

**Comment by acdha** [comment]
Thanks! I'm going to be away for the weekend but will try to review it next week.

**Comment by ke4roh** [comment]
I'd love to get this in!
