### ISSUE TITLE
AttributeError: 'Solr' object has no attribute 'ping'

### ISSUE THREAD

**Issue by lukemaxwell** [django-haystack/pysolr#260]
The latest version [3.8.1] installed via pip seems to be missing the `ping()` method:
```
$ pip install --no-cache pysolr
Collecting pysolr
  Downloading https://files.pythonhosted.org/packages/04/26/051cc17798937bd74358ce40e03b125ce21ae9aa018d89e718cb07a0e9e4/pysolr-3.8.1-py2.py3-none-any.whl
```

```
>>> solr = pysolr.Solr('http://localhost:8983/solr/mycore/')
>>> solr.ping()
AttributeError: 'Solr' object has no attribute 'ping'
```

**Comment by acdha** [comment]
That was added after the last release. You should be able to install from master & I can try to find time to ship a release.

**Comment by Dentrax** [comment]
@acdha We're using this in our project. That's awesome! But... We need this `ping()` command to check the status (up/down) of the server. When will you update for PyPI.org? Current version is: `pysolr 3.8.1` We will wait for the latest version. Thank you!

**Comment by acdha** [comment]
@Dentrax have you tested with the current master branch?

**Comment by Dentrax** [comment]
@acdha I haven't tested `master` branch yet. We are using version `3.8.1` via `pip`.

**Comment by vishwasgpai** [comment]
I have tested with both master and pip. It is not working for me.

**Comment by mcilrain** [comment]
Issue is still present via pip, haven't tried master.

**Comment by dav-ell** [comment]
Master has it in it. Pip does not.

**Comment by Zoidmania** [comment]
Reconfirming pip is missing the `Solr.ping()` function.
