### ISSUE TITLE
Grouping support

### ISSUE THREAD

**Issue by anti-social** [django-haystack/pysolr#28]
Solr 3.3 has grouping (collapsing) support: http://wiki.apache.org/solr/FieldCollapsing

So it would be nice to add this feature to pysolr. I've added grouping support that works for me.

https://github.com/anti-social/pysolr/commit/45abcb37d8cc92ead1864133b5eebb244276e82c

**Comment by mlissner** [comment]
Wait, so #31 didn't get merged, and this ticket was closed. But it seems like you're both satisfied with the solution...does grouping exist somewhere in pysolr?

**Comment by mlissner** [comment]
For others that arrive here. Looks like it does exist, but it's undocumented. You can query in the normal way, then find your data in the `grouped` attribute.

**Comment by acdha** [comment]
@mlissner Sorry about that – there's definitely a documentation lapse and the pull request is easy to miss in search (https://github.com/django-haystack/pysolr/pull/43 with the important part being https://github.com/django-haystack/pysolr/commit/5301e78af71046ded0fecdcc468781549ab8b0a5).

https://github.com/django-haystack/pysolr/commit/329896cef73a3fd929aa4a415d02c6c75fa0ff43 is also worth knowing about if you're dealing with still newer features like the collapsing query parser and the Expand component. I used that awhile back to implement https://gist.github.com/acdha/0a66ca23984bc8d607936fecd9c29941 with less invasive changes than the previous grouped backend (https://gist.github.com/acdha/3750774).

**Comment by mlissner** [comment]
Yeah, I was very pleased to discover the `response` attribute. Provides a lot of flexibility to the library, if it doesn't already do what you want it to. Thanks!
