### ISSUE TITLE
3.9.0 release

### ISSUE THREAD

**Issue by jrhoads** [django-haystack/pysolr#302]
This is a great project and I appreciate the work folks have put in to it over the years.

The cursors behavior looks really useful and would seem to warrant a minor version bump.
It doesn't seem to introduce any breaking changes, just progressive enhancement, along with dependency updates.

Would it be possible to get a 3.9 release?

## Configuration

* Operating system version: RHEL7
* Search engine version: Solr 7.4
* Python version: 3.6
* pysolr version: 3.8.1

**Comment by acdha** [comment]
I haven't had much time to work on pysolr so, assuming someone isn't jumping to volunteer as a release manager, what would help the most would be some time testing and updating the release notes, README, etc.

**Comment by acdha** [comment]
I pushed https://github.com/django-haystack/pysolr/releases/tag/v3.9.0 earlier today.

**Comment by jrhoads** [comment]
Thank you Chris
