### ISSUE TITLE
demo add param setting like set start and rows

### ISSUE THREAD

**Issue by ares5221** [django-haystack/pysolr#343]
# I have
* [ ] Tested with the latest release
* [ ] Tested with the current master branch
* [ ] Searched for similar existing issues

## Expected behaviour
support set param like f1 start rows,
## Actual behaviour
method solr.search only support q
## Steps to reproduce the behaviour

1.

## Configuration

* Operating system version:
* Search engine version:
* Python version:
* pysolr version:

**Comment by acdha** [comment]
It's not clear exactly what you're asking for help with but it sounds like you want:

```python
solr.search(q='*:*', start=123, rows=456)
```

You might want to look at the test suite:

https://github.com/django-haystack/pysolr/blob/master/tests/test_client.py
