### ISSUE TITLE
install pysolr in ubuntu failed

### ISSUE THREAD

**Issue by ares5221** [django-haystack/pysolr#351]
# I have
* [ ] Tested with the latest release
* [ ] Tested with the current master branch
* [ ] Searched for similar existing issues

## Actual behaviour
install pysolr with pip ,and show error: ModuleNotFoundError: No module named 'pysolr'
## Steps to reproduce the behaviour

1.

## Configuration

* Operating system version:
* Search engine version:
* Python version:
* pysolr version:

**Comment by acdha** [comment]
I would double-check your install process – pysolr installs without issue in a clean environment so it sounds like you might have something like an install inside a virtual environment which isn't activated by whatever is seeing that import error or vice versa.
