### ISSUE TITLE
Is there a new release for pysolr?

### ISSUE THREAD

**Issue by lyle-w** [django-haystack/pysolr#373]
I saw a commit https://github.com/django-haystack/pysolr/commit/f6169e9681b95c23d04829c5c0102480382e8ea6 to support customized session has been merged to master branch, however, no new release after that, May I know is there a plan for a new release for the package?

**Comment by iglimanaj** [comment]
I am interested in the new release as well. It would solve https://github.com/django-haystack/pysolr/issues/368 too :)

**Comment by ramayer** [comment]
Also looking forward to the next release. 

A workaround until then is to: 

`pip install git+https://github.com/django-haystack/pysolr/`

**Comment by ramayer** [comment]
thx - I'll start testing in our application; but we're only using python for the ETL/Indexing/Ingest side.

**Comment by SaraElkadi** [comment]
Hey @acdha, I'm interested in using this pr https://github.com/django-haystack/pysolr/pull/374/files as I want to do partial update using JSON, it's already merged to master but there is no release or tag
so if it would be possible to have a release or at least tag soon, that would be great

**Comment by craig-matadeen** [comment]
@acdha Hey Chris, pysolr is a package I use extensively in my day to day. How would one get started with assisting in terms of testing? I have a technical background but sadly I'm out of my depth when it comes to testing and collaborating on a project such as pysolr. I also have a server infrastructure at home if that can be useful in the testing process.

**Comment by acdha** [comment]
> @acdha Hey Chris, pysolr is a package I use extensively in my day to day. How would one get started with assisting in terms of testing? I have a technical background but sadly I'm out of my depth when it comes to testing and collaborating on a project such as pysolr. I also have a server infrastructure at home if that can be useful in the testing process.

> Hey @acdha, I'm interested in using this pr https://github.com/django-haystack/pysolr/pull/374/files as I want to do partial update using JSON, it's already merged to master but there is no release or tag so if it would be possible to have a release or at least tag soon, that would be great

There are tags and releases available for testing but they're marked as betas:

https://pypi.org/project/pysolr/3.10.0b1/

That keeps a simple `pip install pysolr` from picking them up but `pip install pysolr==3.10.0b1` will work. I was hoping for someone to report positive results before cutting a release since my time to support pysolr is extremely limited these days.

**Comment by craig-matadeen** [comment]
> > @acdha Hey Chris, pysolr is a package I use extensively in my day to day. How would one get started with assisting in terms of testing? I have a technical background but sadly I'm out of my depth when it comes to testing and collaborating on a project such as pysolr. I also have a server infrastructure at home if that can be useful in the testing process.
> 
> > Hey @acdha, I'm interested in using this pr https://github.com/django-haystack/pysolr/pull/374/files as I want to do partial update using JSON, it's already merged to master but there is no release or tag so if it would be possible to have a release or at least tag soon, that would be great
> 
> There are tags and releases available for testing but they're marked as betas:
> 
> https://pypi.org/project/pysolr/3.10.0b1/
> 
> That keeps a simple `pip install pysolr` from picking them up but `pip install pysolr==3.10.0b1` will work. I was hoping for someone to report positive results before cutting a release since my time to support pysolr is extremely limited these days.

Hey @acdha is there a list of things that needs checking to ensure that things are in top order, like a check-list of items to verify works? I can spend some time over this weekend testing them out.

**Comment by ch2ohch2oh** [comment]
Any new thoughts about releasing after the long silence?

**Comment by acdha** [comment]
You're right, this is long overdue. pysolr really needs a more active maintainer.

I just cut https://pypi.org/project/pysolr/3.10.0b2/ with the changes since b1. If I don't hear any problems reported in the discussions I'll publish v3.10.0 next week:

https://github.com/django-haystack/pysolr/releases/tag/v3.10.0b2

**Comment by ramayer** [comment]
Looks good to me!

**Comment by superkelvint** [comment]
@acdha I work at [SearchStax](https://www.searchstax.com/), a managed Solr hosting provider. Since we use pysolr internally, we'd be happy to take on some the work maintaining this repo. I sent you a LI connect where we can chat.

**Comment by ericsouza** [comment]
hey @acdha any news on the v3.10.0 release?

**Comment by acdha** [comment]
> hey @acdha any news on the v3.10.0 release?

Thanks for the reminder: https://pypi.org/project/pysolr/3.10.0/

**Comment by ramayer** [comment]
Awesome!   [would have been nice to be added to the changelog for #357 / #358 - but I'm happy to see we no longer need to maintain or own fork at work]
