### ISSUE TITLE
extract could use ExtractingRequestHandler better

### ISSUE THREAD

**Issue by galund** [django-haystack/pysolr#44]
The comments for the "extract" method state that ExtractingRequestHandler "is rarely useful as it allows no way to store additional data or otherwise customize the record. Instead, by default we'll use the extract-only mode..."

This is out-of-date (if it was ever true), as the documentation http://wiki.apache.org/solr/ExtractingRequestHandler states clearly that you can submit additional fields by preceding their name with "literal.".

The current implementation leads to odd, inefficient code that first sends the document, then re-posts the result to get the extracted text into the index.

Am I missing something?

Now that extract allows for additional keyword arguments, is it just a case of updating the docstring, or could a better interface be made?

**Comment by acdha** [comment]
@galund The comment was true when originally authored. Since by now we can assume most people have upgraded to a version of Solr which supports it or Solr 4's atomic updates, it'd probably make sense to create a pull-request which accepts the literal values and automatically sets `extractOnly=False` when provided.

**Comment by sethmachine** [comment]
I believed this was a problem with the "extract" method as well based on its docstring.  Based on this issue, this technically appears "unsolved", so I'm making this comment for anyone else who might be confused.  

However, you can use keyword arguments now to pass additional metadata fields a single HTTP POST, e.g.

```python
    infile = 'foobar.pdf'
    with open(infile, 'rb') as f:
        res = solr.extract(f, extractOnly=False, **{'literal.blah_s': 'foobar'})
        solr.commit()
```
The document will now have a field called "blah_s" with value "foobar."
