### ISSUE TITLE
DeprecationWarning from pkg_resources on Python 3.10+

### ISSUE THREAD

**Issue by craigds** [django-haystack/pysolr#464]
# I have
* [x] Tested with the latest release
* [x] Tested with the current master branch
* [x] Searched for similar existing issues

## Expected behaviour

pysolr can be imported without warnings

## Actual behaviour

pysolr causes a deprecation warning from importing pkg_resources on Python 3.10+

## Steps to reproduce the behaviour

```
$ python -W ::DeprecationWarning -c 'import pysolr'

/venv/lib/python3.10/site-packages/pysolr.py:14: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import DistributionNotFound, get_distribution, parse_version
```

## Configuration

* Operating system version: Ubuntu 22.04 LTS
* Search engine version:
* Python version: Python 3.10.12
* pysolr version: `3.10.0b2`

**Comment by cclauss** [comment]
This is a warning, not an error.  This software does not have a problem functioning on Python 3.12.

**Comment by craigds** [comment]
correct. (still needs to be fixed, so i've submitted a PR^)
