### ISSUE TITLE
pysolr should support custom handlers

### ISSUE THREAD

**Issue by llnik** [django-haystack/pysolr#51]
Solr provides the creation of various handlers for different purposes in solrconfig.xml - so, one could have a "/solr/select handler for default searching and a /solr/articlesearch for searching with some different filters and different settings.

In pysolr, however, only the default handlers (/solr/select, /solr/update, etc.) can be used.

**Comment by mbeacom** [comment]
@toastdriven @acdha Are you still actively merging pull requests?  Can we please get some of these patches merged in or explanation as to why they were rejected?  Thank you!

**Comment by acdha** [comment]
@mbeacom If you need either of these, the first place to start would be updating the code against the current branch to confirm that there are no test regressions. I work on pysolr in my spare time so anything which makes review easier is going to help.

**Comment by mbeacom** [comment]
@acdha I am not trying to add more work for you.  I'll go ahead and get it up to speed.  Thank you!

**Comment by mbeacom** [comment]
@acdha https://github.com/toastdriven/pysolr/pull/161

**Comment by nuarhu** [comment]
I've rebased (again) onto the current master. Is there a problem or are there considerations that prevent you from merging this? We are using this in production without issues, so far.
