### ISSUE TITLE
unicode_literals does not work with lxml

### ISSUE THREAD

**Issue by thomasbilk** [django-haystack/pysolr#91]
When I want to add documents through pysolr with lxml installed I get this error: 

```
TypeError: Element() keywords must be strings
```

This is due to the unicode_literals import that convert the keys of the `attrs` dictionary to unicode and lxml (2.3.2) does not like unicode keys. The `xml.etree` version seems to work.

**Comment by toph-allen** [comment]
I'm running into this issue too. It's a problem when trying to write Python 2- and 3- compatible code.
